version: '3.8'
services:

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: algo_db
    ports:
      - "3306:3306"


  app:
    build: .
    container_name: java_bot
    restart: always
    depends_on:
      - db
    ports:
      - "7070:7070"

    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/algo_db